# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ec5842d482915ac93b1c300bd861f04879aaa58149ce9ec1d51e2900ceae175dcb23cc288d639fa83efd34ed49f5092ede93410c2659d19e92324c7dca7f6e

test:
  secret_key_base: 61eab48c59b7e248d74f8e845beb079c6fe0973d374fd52e2f3221d75ad6c3d6c8bdff7eb97b1babeb53c184288736f89acd0d345844a1ed97ad2f7945e727b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
